/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserDTO,
  UserUpdateDTO,
} from '../models/index';
import {
    UserDTOFromJSON,
    UserDTOToJSON,
    UserUpdateDTOFromJSON,
    UserUpdateDTOToJSON,
} from '../models/index';

export interface UpdateUserInfosRequest {
    dataToUpdate: UserUpdateDTO;
}

/**
 * 
 */
export class UserControllerApi extends runtime.BaseAPI {

    /**
     */
    async getUserInfosRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue));
    }

    /**
     */
    async getUserInfos(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO> {
        const response = await this.getUserInfosRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateUserInfosRaw(requestParameters: UpdateUserInfosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserDTO>> {
        if (requestParameters['dataToUpdate'] == null) {
            throw new runtime.RequiredError(
                'dataToUpdate',
                'Required parameter "dataToUpdate" was null or undefined when calling updateUserInfos().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dataToUpdate'] != null) {
            queryParameters['dataToUpdate'] = requestParameters['dataToUpdate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateUserInfos(requestParameters: UpdateUserInfosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserDTO> {
        const response = await this.updateUserInfosRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
