FROM httpd:2.4

# Enable SSL and proxy modules
RUN sed -i 's/#LoadModule ssl_module/LoadModule ssl_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/#LoadModule rewrite_module/LoadModule rewrite_module/' /usr/local/apache2/conf/httpd.conf && \
    echo "LoadModule proxy_module modules/mod_proxy.so" >> /usr/local/apache2/conf/httpd.conf && \
    echo "LoadModule proxy_http_module modules/mod_proxy_http.so" >> /usr/local/apache2/conf/httpd.conf && \
    echo "LoadModule headers_module modules/mod_headers.so" >> /usr/local/apache2/conf/httpd.conf

# Set global ServerName
RUN echo "ServerName app.louisplace.com" >> /usr/local/apache2/conf/httpd.conf

# Include our custom config
RUN echo "Include conf/extra/next_app.conf" >> /usr/local/apache2/conf/httpd.conf

# Copy custom Apache config
COPY conf/ /usr/local/apache2/conf/extra/