FROM httpd:2.4

# Enable SSL
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-apache && \
    rm -rf /var/lib/apt/lists/*

RUN echo "ServerName app.louisplace.com" >> /usr/local/apache2/conf/httpd.conf

RUN echo "Include conf/extra/next_app.conf" >> /usr/local/apache2/conf/httpd.conf

COPY conf/ /usr/local/apache2/conf/extra/

# Expose ports
EXPOSE 80 443