FROM httpd:2.4

ENV HTTPD_CONF_DIR /usr/local/apache2/conf/httpd.conf

# Set global ServerName
RUN echo "ServerName app.louisplace.com" >> $HTTPD_CONF_DIR

RUN sed -i 's/#LoadModule ssl_module/LoadModule ssl_module/' $HTTPD_CONF_DIR && \
    sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' $HTTPD_CONF_DIR && \
    sed -i 's/#LoadModule socache_shmcb_module/LoadModule socache_shmcb_module/' $HTTPD_CONF_DIR

# Include our custom config
RUN echo "Include conf/extra/next_app.conf" >> $HTTPD_CONF_DIR

